[versions]
annotations = "26.0.2"
gson = "2.13.1"
slf4j = "2.0.17"

[libraries]
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }