name: Publish - Snapshot
on:
  push

jobs:
  publish:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Determine Version
        id: version
        run: |
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          GIT_HASH=$(git rev-parse HEAD)

          VERSION="${GIT_BRANCH}-${GIT_HASH:0:7}"
          
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Version: ${VERSION}" >> $GITHUB_STEP_SUMMARY

      - name: Publish Artifacts
        run: ./gradlew publish
        env:
          REPO_USERNAME: ${{ secrets.REPOSITORY_USER }}
          REPO_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
          RELEASE: false
          VERSION: ${{ steps.version.outputs.version }}